home-myhome-build:
  only:
    changes:
      #      - components/home-module/myhome/*.{java,kt,xml,gradle}
      - android/components/home-module/myhome/**/*
  stage: build
  script:
    - ./gradlew :components:home-module:myhome:assemble


#home-myhome-lint:
#  only:
#    changes:
#      - android/components/home-module/myhome/**/*
#  stage: test
#  script:
#    - ./gradlew :components:home-module:myhome:lintInhouse

home-myhome-deploy:
  only:
    changes:
      - android/components/home-module/myhome/**/*
  stage: deploy
  script:
    - ./gradlew :components:home-module:myhome:publishDebugAarPublicationToMavenCentralRepository #发布到远程仓库

## ========================
#home-daily-check:
#  only:
#    changes:
#      - android/components/home-module/**/*
#  stage: build
#  script:
#    - ./gradlew :components:home-module:main:fileCounter

##debugTests:
##  stage: test
##  script:
##    - ./gradlew -Pci --console=plain :app:testDebug
#