# 确保fwk每个修改点都输出最新的fwk包给上层
fwk-common-build:
  only:
    changes:
      - android/framework/common/**/*
  stage: build
  script:
    - ./gradlew :framework:common:assemble publishDebugAarPublicationToMavenCentralRepository
# ========================
fwk-av-build:
  only:
    changes:
      - android/framework/av/**/*
  stage: build
  script:
    - ./gradlew :framework:av:assemble publishDebugAarPublicationToMavenCentralRepository
# ========================
#fwk-flutter:
#  only:
#    changes:
#      - android/framework/flutter/**/*
#  stage: build
#  script:
#    - ./gradlew :framework:flutter:build
# ========================
fwk-hybrid-build:
  only:
    changes:
      - android/framework/hybrid/**/*
  stage: build
  script:
    - ./gradlew :framework:hybrid:assemble publishDebugAarPublicationToMavenCentralRepository
# ========================
fwk-image-build:
  only:
    changes:
      - android/framework/image/**/*
  stage: build
  script:
    - ./gradlew :framework:image:assemble publishDebugAarPublicationToMavenCentralRepository
# ========================
#fwk-map:
#  only:
#    changes:
#      - android/framework/map/**/*
#  stage: build
#  script:
#    - ./gradlew :framework:map:assemble publishDebugAarPublicationToMavenCentralRepository includeBinaryModule  -PmoduleList=framework-map
#    - ./gradlew :framework:loader:assemble publishDebugAarPublicationToMavenCentralRepository
# ========================
#fwk-mockserver:
#  only:
#    changes:
#      - android/framework/mockserver
#  stage: build
#  script:
#    - ./gradlew :framework:mockserver:build
#     - ./gradlew :framework:loader:assemble
# ========================
fwk-network-build:
  only:
    changes:
      - android/framework/network/**/*
  stage: build
  script:
    - ./gradlew :framework:network:assemble publishDebugAarPublicationToMavenCentralRepository
# ========================
fwk-storage-build:
  only:
    changes:
      - android/framework/storage/**/*
  stage: build
  script:
    - ./gradlew :framework:storage:assemble publishDebugAarPublicationToMavenCentralRepository
# ========================
fwk-loader-build:
  only:
    changes:
      - android/framework/loader/**/*
  stage: build
  script:
    - ./gradlew :framework:loader:assemble publishDebugAarPublicationToMavenCentralRepository
# ========================
#buildBigApp job
#build-big-app:
#  stage: build
#  script:
#    - ./gradlew buildBigApp
#  #    - ./gradlew reportMappingDebug  &&  ./gradlew reportSoDebug
#  artifacts:
#    paths:
#      - app/build/outputs/app-release.apk
#dailyCheck:
#  only:
#    - master
#  stage: build
#  script:
#    #    - ./gradlew :app:fileCounter
#    - ./gradlew :app:dangerousApiTask
#deploy2Firebase:
#  only:
#    - master
#  stage: deploy
#  script:
#    - ./gradlew :app:appDistributionUploadRelease
#deploy2Pgyer:
#  only:
#    - master
#  stage: deploy
#  script:
#    - ./script/pgyer_upload.sh "${CI_PROJECT_DIR}/app/build/outputs/apk/release/app-release.apk" $PG_API_KEY $PG_APP_KEY ${CI_PROJECT_DIR}
#    - echo "deploy to pgyer"
# ========================


#lint job
#lintDebug:
#  only:
#    - master
#  stage: build
#  #  before_script:#会覆盖最外层的before_script流程
#  #    - echo "lint before script"
#  script:
#    - ./gradlew -Pci --console=plain -PbuildDir=lint :app:lintDebug

#debugTests:
#  stage: test
#  script:
#    - ./gradlew -Pci --console=plain :app:testDebug

#docker build:
#  script: docker build -t my-image:$CI_COMMIT_REF_SLUG .
#  only:
#    changes:
#      - Dockerfile #The Dockerfile file
#      - docker/scripts/* #Any of the files inside docker/scripts/ directory.
#      - dockerfiles/**/*  #Any of the files and subdirectories inside the dockerfiles directory.
#      - more_scripts/*.{rb,py,sh} #Any of the files with rb, py, sh extensions inside the more_scripts directory.
